import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import { useAppDispatch, useAppSelector } from "../redux/hooks";
import { getServices } from "../redux/features/serviceSlice";
import styles from "../styles/Home.module.css";
import { getCategory } from "../redux/features/categorySlice";

const Home: NextPage = () => {
  const dispatch = useAppDispatch();

  useEffect(() => {
    dispatch(getServices());
    dispatch(getCategory());
  }, []);

  const { services, categoriesState } = useAppSelector((reducer: any) => ({
    services: reducer.service.items,
    categoriesState: reducer.category.items,
  }));

  console.log(services, categoriesState);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>
        Welcome to <a href="https://nextjs.org">Next.js!</a>
      </h1>
    </div>
  );
};

export default Home;
